---
- name: with_items.yml
  hosts: all
  tasks:
  - name: install packages
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
      force_apt_get: yes
    with_items:
    - apache2
    - docker*

  - name: start services
    service:
      name: "{{item}}"
      state: started
    with_items:
    - apache2
    - docker
